95 grafiken 2
zhaw-it19tb-win/unity-crawler pull request #17
Opened 2022-04-14 08:41 UTC by ProCarpet

Added moving animation for playercharacter

2022-04-17 21:54 UTC, lukasbischof commented
@ProCarpet FYI, required checks laufed ned, will ned uf em aktuelle main bisch. Sobald uf de main rebased hesch, setted die au laufe

2022-04-24 12:03 UTC, MrHanky96 commented
Spieler ist nicht sichtbar. Manchmal kann man den Hut sehen....

2022-04-24 12:05 UTC, MrHanky96 requested changes
Fix player visibility

2022-04-24 15:48 UTC, lukasbischof commented
Can you please remove the .idea folder?

2022-04-24 15:55 UTC, MrHanky96 approved these changes

2022-04-24 15:56 UTC, merged