Added Effects
zhaw-it19tb-win/unity-crawler pull request #27
Opened 2022-04-28 17:14 UTC by meyenjan

2022-04-29 08:35 UTC, pascalgoetz requested changes
-Compiler Error in Health.cs
-Alten Code aufräumen der nicht mehr gebraucht wird (z.B. WitchShooting)

2022-04-29 08:39 UTC, pascalgoetz commented
@meyenjan 
Ich habe dir noch den Bug zugewiesen, da der anscheinend geflickt ist in deinem Branch

2022-05-02 21:04 UTC, meyenjan commented
@pascalgoetz 
WitchShooting kann noch benutzt werden
Movement der Fähigkeit ist jetzt einfach via ".position +=" gelöst, was eventuell dazu führt, dass Fähigkeiten durch Wände fliegen etc.
Die Idee war fürs erste einen Skillshot wie der jetzige Linksklick, der einfach mit einer fixen Geschwindigkeit fliegt.
Dann zusätzlich eine Fähigkeit, die einfach am Mausklick erscheint.
Und eventuell dann wie in WitchShooting eine Fähigkeit, die mit der Physik interagiert und eventuell auch Gegner wegstossen kann etc.

2022-05-03 16:35 UTC, pascalgoetz approved these changes

2022-05-03 16:35 UTC, merged